const tipoProducto = ["clothes", "electronics", "futernitures", "toys", "others"];
const productList = [
{
    name: 'Chaleco Scott De Hombre',
    price: 32990,
    image: './images/Chaleco.png',
    type: tipoProducto[0],
    description: "Chaleco de Nylon matelaseado, con cuello alto. Acceso frontal con cierre plástico. Dos bolsillos ojal con cierre invisible. Sisa elástica. Bolsillos internos.",
    id: 0,
},
{
    name: 'Campera Macowens Deportiva Clásica Azul Hombre',
    price: 19999,
    image: './images/Campera.png',
    type: tipoProducto[0],
    description: "Campera tipo deportiva con capucha. De color azul marino. Cuenta con cierre central y bolsillos waterproof. Un bolsillo en el pecho y dos en los laterales. Ideal para un look casual.",
    id: 1,
},
{
    name: 'Remera Gold Coast De Mujer 47 Steet',
    price: 8999,
    image: './images/Remera.png',
    type: tipoProducto[0],
    description: "Remera manga corta de jersey con cuello redondo aplicado. Detalle de dobladillo en ruedo de manga. Largo a la cadera. Molderia cuadrada. Estampa centrada en frente.",
    id: 2,
},
{
    name: 'Sweater Hoddied Copenhague Marfil Mujer',
    price: 13455,
    image: './images/Sweater.png',
    type: tipoProducto[0],
    description: "Hoddie de calce holgado, manga larga con lazo para atar.",
    id: 3,
},
{
    name: 'Camisa Carol Army Wanama Oficial',
    price: 22990,
    image: './images/Camisa.png',
    type: tipoProducto[0],
    description: "Camisa de calce amplio con charreteras en hombros, con bolsillos en delanteros, acceso por cartera delantera con botones. puños con botón.",
    id: 4,
},
{
    name: 'Aire Acondicionado Philco split frío/calor',
    price: 274999,
    image: './images/Aire.png',
    type: tipoProducto[1],
    description: "Climatizar tus espacios a lo largo del año es sin duda algo importante para tu comodidad y la de tus seres queridos. Contar con un aire acondicionado con función frío/calor es la mejor decisión. Con este aire Philco conseguí una mejor relación costo-beneficio.",
    id: 5,
},
{
    name: 'Ventilador de pared y de piso Indelplas IV16 negro',
    price: 9508,
    image: './images/Ventilador.png',
    type: tipoProducto[1],
    description: "¡Aire limpio y fresco en tus ambientes! El ventilador Indelplas IV16 es un elemento útil para dar frescura en el hogar. Con su óptimo rendimiento, la sensación térmica disminuirá. Es un aparato práctico, fácil de armar e instalar.",
    id: 6,
},
{
    name: 'Microondas Grill Samsung MG23F3K3TA negro',
    price: 46990,
    image: './images/Microondas.png',
    type: tipoProducto[1],
    description: "No pierdas tiempo en la cocina. En simples pasos, podés disfrutar de tus comidas favoritas gracias a la tecnología y evolución de Samsung. El mismo cuenta con recetas preprogramadas para tu comodidad. Cocina fácilmente todo, desde arroz integral hasta pechuga de pollo deshuesada y filetes de salmón a la parrilla, con la garantía de que el resultado será comida fresca y sabrosa.",
    id: 7,
},
{
    name: 'Lavarropas automático Samsung WW90AA46B',
    price: 209999,
    image: './images/Lavarropas.png',
    type: tipoProducto[1],
    description: "Únicamente necesita que se introduzcan los productos de limpieza y se elija el programa deseado. A diferencia de los semiautomáticos, no requiere que estés presente en todas las etapas del proceso, por lo que vas a tener prendas limpias y perfumadas sin esfuerzo.",
    id: 8,
},
{
    name: 'Heladera Gafa HGF388AFB blanca con freezer',
    price: 174299,
    image: './images/Heladera.png',
    type: tipoProducto[1],
    description: "Disfrutá de tus alimentos frescos y almacenalos de manera práctica y cómoda en la heladera Gafa, la protagonista de la cocina.",
    id: 9,
},
{
    name: 'Mesa De Escritorio Con Bandeja Para Teclado Nogal',
    price: 17800,
    image: './images/Escritorio.png',
    type: tipoProducto[2],
    description: "La solución para tu casa u oficina está en el escritorio Máximo 100, no ocupa mucho espacio y cabe perfecto tu pc o notebook. Es fácil de armar (incluye manual de instrucciones) y la calidad de los materiales es excelente.",
    id: 10,
},
{
    name: 'Estanteria Biblioteca Nordica Escandinava Moderna',
    price: 21290,
    image: './images/Estanteria.png',
    type: tipoProducto[2],
    description: "El mueble va ARMADO. Por favor tomalo en cuenta al ver cómo ingresarlo a tu domicilio.",
    id: 11,
},
{
    name: 'Mueble Panel Tv 32 A 50 Modular Rack',
    price: 17990,
    image: './images/Mueble-Tele.png',
    type: tipoProducto[2],
    description: "La publicación corresponde a 1 panel para tv colgante, ¡APTO PARA TV DE HASTA 45 PULGADAS! Melamina 18 mm Cantos en PVC",
    id: 12,
},
{
    name: 'Sillón Gamer Masajeador Apoya Pie Silla Reclinable',
    price: 52249,
    image: './images/Sillon-Gamer.png',
    type: tipoProducto[2],
    description: "// SILLÓN GAMER MASAJEADOR //",
    id: 13,
},
{
    name: 'Cama Hierro Madera Industrial Caño Estructural Queen',
    price: 85000,
    image: './images/Cama.png',
    type: tipoProducto[2],
    description: "Cama industrial quuen",
    id: 14,
},
{
    name: 'Juego de mesa Crazy gorilla Ditoys 611',
    price: 3620,
    image: './images/Gorilla.png',
    type: tipoProducto[3],
    description: "¿Qué mejor plan para una tarde de lluvia que un juego de mesa? Con el Crazy gorilla vas a crear divertidos recuerdos y pasar momentos inolvidables junto a tus amigos y amigas. Con este pasatiempo entretenido las risas están aseguradas.",
    id: 15,
},
{
    name: 'Figura de acción Señor Cara de Papa de Hasbro Plasyskool',
    price: 4500,
    image: './images/Cara de Papa.png',
    type: tipoProducto[3],
    description: "Al tener marcadas las articulaciones podrás manejar y acomodar tus figuras como más te guste. Con ellas, vas a poder crear historias en la que los personajes puedan movilizarse y cobrar vida.",
    id: 16,
},
{
    name: 'Muñeca Barbie Básica Modelo Nuevo',
    price: 4995,
    image: './images/Barbie.png',
    type: tipoProducto[3],
    description: "Muñeca Barbie Básica Modelo Nuevo T7439",
    id: 17,
},
{
    name: 'Juego de mesa Ludo matic Habano',
    price: 1688,
    image: './images/Ludo.png',
    type: tipoProducto[3],
    description: "¡Para aprender y disfrutar jugando! El juego Ludo matic está pensado para desarrollar habilidades y potenciar las capacidades cognitivas y creativas de las y los niños. Ejercitarán el pensamiento y la concentración, a la vez que se divierten con este método de aprendizaje lúdico y relajado.",
    id: 18,
},
{
    name: 'Peluche Rainbow Friends Amigo Arcoiris',
    price: 1869,
    image: './images/Peluche.png',
    type: tipoProducto[3],
    description: "Peluches de los personajes de RAINBOW FRIENDS DEL VIDEOJUEGO DE ROBLOX",
    id: 19,
},
{
    name: 'Ford Bronco 2.0 T Sport Wildtrak 2023',
    price: 18612700 ,
    image: './images/Bronco.png',
    type: tipoProducto[4],
    description: "La unidades se entregan el mismo dia que se abona el vehiculo, con la mejor atencion, Confiabilidad, Servicio y Gestoria en la actualidad del mercado. Solicite su turno para ver tu vehiculo!!",
    id: 20,
},
{
    name: 'Stereo Auto Doble Din Pantalla Tactil',
    price: 20069,
    image: './images/Stereo.png',
    type: tipoProducto[4],
    description: "Increíble estéreo doble DIN de pantalla de 7 Pulgadas con soporte de definición Full HD 1080p, para ver películas, fotos y tener una conectividad total bluetooth con tus dispositivos.",
    id: 21,
},
{
    name: 'Batería De Auto Herbo 12x75',
    price: 24300,
    image: './images/Bateria.png',
    type: tipoProducto[4],
    description: "En caso de requerir la instalación se debe dejar la batería usada según la Ley N° 24051 a favor del medio ambiente.",
    id: 22,
},
{
    name: 'Pistola De Calor Daewoo Con Accesorios En Kit',
    price: 8940,
    image: './images/Pistola de calor.png',
    type: tipoProducto[4],
    description: "Producto nuevo y sellado.",
    id: 23,
},
{
    name: 'Amoladora Angular Daewoo',
    price: 16180,
    image: './images/Amoladora.png',
    type: tipoProducto[4],
    description: "Daewoo ofrece una amplia variedad de líneas de productos, todas ellas específicamente pensadas y diseñadas para brindar la máxima satisfacción.",
    id: 24,
}
];